### ISSUE TITLE
Not all friends showing up on map

### ISSUE THREAD

**Issue by wikiworldorder** [wikiworldorder/burnermap#3]
Not all of my Facebook friends — who have signed up to use the app this year — are appearing on my map. I am not sure if this issue is related to users who first connected before the switch to the new Socialite connection.

**Comment by wikiworldorder** [comment]
Absent a solution for the inadequate friends list I’m pulling from the Facebook connection, the Map page is [temporarily] looking for all friend matches from previous years. This has filled out my map much more appropriately, though I am still uncertain if this patch is thorough. Nonetheless, the friend list retrieval still needs to be fixed.

**Comment by nicole-disqus** [comment]
Having the same issue. My friend was able to submit his info before the recent switch, though I was unable to. Now that I'm able to see the map, he doesn't show up, not as someone who has submitted their info, nor as someone who has not yet submitted for this year (he has used the map the past few years). However he says that I show up on his map.

**Comment by nicole-allard** [comment]
Having the same issue. My friend was able to submit his info before the recent switch, though I was unable to. Now that I'm able to see the map, he doesn't show up, not as someone who has submitted their info, nor as someone who has not yet submitted for this year (he has used the map the past few years). However he says that I show up on his map.

**Comment by leah** [comment]
Maybe it's just a pagination issue? It looks like the Facebook Graph API paginates lists of friends.

I'm new to the BurnerMap this year and my list is WAY shorter than it should be. I only see 3 friends, though I know of over 20 friends going. This makes me think that I'm not getting many matches through Facebook at all.

Here's the bit of code that I think is coming up a bit short on friends: https://github.com/wikiworldorder/burnermap/blob/master/src/Controllers/FaceController.php#L176-L179

I think it might be fixed by using the cursor to go though all pages of friends. I don't know PHP, otherwise I'd try to fix it myself and send a PR.

https://developers.facebook.com/docs/graph-api/reference/user/friends/
https://developers.facebook.com/docs/graph-api/using-graph-api/#paging

Hope it's helpful anyway! ❤️

**Comment by wikiworldorder** [comment]
This is SUPER helpful, Leah! Thank you, I think I've just applied the fix!! <3

**Comment by leah** [comment]
Yayyy! I now have 26 friends showing up, which seems perfect. So glad you were able to fix this so quickly! Thank you so much @wikiworldorder!
